

    <form id="addReal" enctype="multipart/form-data" method="POST" action="addReal.php"  class="form-group container d-flex  text-center col-sm-8 col-sm-offset-8">
    <section>

    <div class="form-group"> 
        <label for="real_name">Nom de la réalisation</label>
        <input id="real_name" name="real_name" type="text">
    </div>
    <div class="form-group">
        <label for="real_pres">Présentation de la réalisation</label>
        <input id="real_pres" name="real_pres" type="textarea">
    </div>
    <div class="form-group">
        <label for="real_photos_1">Fichier:</label>
        <input type="hidden" name="MAX_FILE_SIZE" value="15000000" />
        <input type="file" name="real_photos[]" id="real_photos_1" />
        <p>'Fichiers de type '
    </div>
    <div class="form-group">
        <label for="real_photos_2">Fichier:</label>
        <input type="hidden" name="MAX_FILE_SIZE" value="15000000" />
        <input type="file" name="real_photos[]" id="real_photos_2" />
    </div>
    <div class="form-group">
        <label for="real_photos_3">Fichier:</label>
        <input type="hidden" name="MAX_FILE_SIZE" value="15000000" />
        <input type="file" name="real_photos[]" id="real_photos_3" />
    </div>
            <input type="submit" value="valider">
            </section>