

    <form id="addReal" method="POST" action="addReal.php" >
    <section class="form-group container d-flex justify-content-center text-center col-sm-8 col-sm-offset-8">

    <div class="form-group"> 
        <label for="real_name">Nom de la réalisation</label>
        <input id="real_name" name="real_name" type="text">
    </div>
    <div class="form-group">
        <label for="real_pres">Présentation de la réalisation</label>
        <input id="textarea" name="real_pres" type="text">
    </div>
    <div class="form-group">
        <label for="real_photos_1">Fichier:</label>
        <input type="hidden" name="MAX_FILE_SIZE" value="1048576" />
        <input type="file" name="imageArticle" id="imageArticle" />
    </div>
            <input type="submit" value="valider">
            </section>