<!DOCTYPE html>
<html lang="fr">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?=$title?></title>

    <!-- Bootstrap core CSS -->
    <link href="../vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!--Datatable -->
    <link href="http://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css
" rel="stylesheet">
      <!-- Bootstrap core JavaScript -->
    <script src="../../js/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="../../css/bootstrap-4.2.1-dist/table.css" crossorigin="anonymous">
    <link rel="stylesheet" href="../../css/bootstrap-4.2.1-dist/css/bootstrap.min.css" crossorigin="anonymous">
    <script src="http://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
  </head>

  <body>

    <!-- Page Content -->
    <div class="container d-flex justify-content-center">

        <div class="col-sm-4 col-sm-offset-4">
          <div>
            <img src="../../img/logo.png" width="370" height="200">
          </div>
          <h1 class="mt-5"><?=$title?></h1>

			<form role="form" action="login.php" method="POST">
		  
				<fieldset>
					<div class="form-group">
						<input class="form-control" placeholder="Pseudo" name="pseudo" type="text" autofocus>
					</div>
					<div class="form-group">
						<input class="form-control" placeholder="Password" name="password" type="password" value="">
					</div>
					<div class="checkbox">
						<label for="remember">Se souvenir de moi</label>
							<input name="remember" id="remember" type="checkbox" value="Remember Me">	
					</div>
					<input type="submit" value="Login">
				</fieldset>
			</form>
        </div>
    </div>


    

  </body>

</html>



 