<section class="content">
    <article>
        <h1>BUSY</h1>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nulla, esse consectetur autem corrupti, saepe voluptatum architecto nisi, repudiandae similique fugit fuga aliquid! Recusandae consequuntur corporis sed alias aut cum, expedita ipsam perferendis, obcaecati qui laborum nihil suscipit enim nam illum ducimus eos. Non iste, quas optio veniam officia nostrum minus.</p>
    </article>
    