<section class="fullDisplay pitch">
        <div></div>
        <article>
            <h1>Busy Designs</h1>
            <p>Design contemporain, s'adaptant à votre vie.</p>
        </article>
        <div></div>
    </section>
    <section class="fullDisplay">
        <section class="content noOpacity">
            <section class="overView" >
                <article>
                    <h2>Réalisations</h2>
                    <span> <span></span></span>
                    <div id="slider1" class="flexslider">
                            <ul class="slides">
                                <li>
                                <img src="img/img3.jpg" alt="logo"/>
                                </li>
                                <li>
                                <img src="img/img2.jpg" alt="logo"/>
                                </li>
                                <li>
                                <img src="img/img1.jpg" alt="logo"/>
                                </li>
                            </ul>
                    </div>
                    <span>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores enim maiores, odit eius nesciunt neque consectetur deserunt ipsum optio cumque deleniti atque distinctio porro ut at, obcaecati doloremque. Nobis ipsam inventore magni, accusamus corrupti minus provident ratione ad sapiente iure quo, maxime aliquam, distinctio sed in quos similique deserunt a debitis nostrum culpa at saepe doloribus. Architecto reprehenderit quos dolorum.
                        </p>
                        <ul>
                            <li><p><a href="#">Realisation 1</a></p></li>
                            <li><p><a href="#">Réalisation 2</a></p></li>
                            <li><p><a href="#">Réalisation 3</a></p></li>
                        </ul>
                    </span>

                </article>

                <article>

                    <h2>Impressions 3D</h2>
                    <span> <span></span></span>
                    <span>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores enim maiores, odit eius nesciunt neque consectetur deserunt ipsum optio cumque deleniti atque distinctio porro ut at, obcaecati doloremque. Nobis ipsam inventore magni, accusamus corrupti minus provident ratione ad sapiente iure quo, maxime aliquam, distinctio sed in quos similique deserunt a debitis nostrum culpa at saepe doloribus. Architecto reprehenderit quos dolorum.
                        </p>
                    </span>
                    <div id="slider1" class="flexslider">
                                <ul class="slides">
                                    <li>
                                    <img src="img/img1.jpg" alt="logo"/>
                                    </li>
                                    <li>
                                    <img src="img/img2.jpg" alt="logo"/>
                                    </li>
                                    <li>
                                    <img src="img/img3.jpg" alt="logo"/>
                                    </li>
                                </ul>
                    </div>
                </article>

                <article >

                    <h2>A Propos</h2>
                    <span> <span></span></span>
                    <span class="fullDisplay"></span>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores enim maiores, odit eius nesciunt neque consectetur deserunt ipsum optio cumque deleniti atque distinctio porro ut at, obcaecati doloremque. Nobis ipsam inventore magni, accusamus corrupti minus provident ratione ad sapiente iure quo, maxime aliquam, distinctio sed in quos similique deserunt a debitis nostrum culpa at saepe doloribus. Architecto reprehenderit quos dolorum.
                    </p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores enim maiores, odit eius nesciunt neque consectetur deserunt ipsum optio cumque deleniti atque distinctio porro ut at, obcaecati doloremque. Nobis ipsam inventore magni, accusamus corrupti minus provident ratione ad sapiente iure quo, maxime aliquam, distinctio sed in quos similique deserunt a debitis nostrum culpa at saepe doloribus. Architecto reprehenderit quos dolorum.
                    </p>
                </article>
            </section>    
        </section>
  