<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta description="Busy Designs - LOREM IPSUM">
    
    <script src="js/jquery-3.3.1.min.js" type="text/javascript"></script>
    <script src="js/script.js"></script>

    <!-- SLIDER -->
    <link rel="stylesheet" href="js/slider/flexslider.css" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
    <script src="js/slider/jquery.flexslider.js"></script>
    

    <!-- FIN SLIDER -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,400" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">

    
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/main.css">
   
   

    <title>Busy Designs - Acceuil</title>
</head>

<header class="fullDisplay jsFixed">
    <img src="img/logo.png" class="logo" id="logo" alt="logo">
    <nav class=" noOpacity">   
        <a href="#" class="link fromRight">Réalisations</a>
        <a href="#" class="link">Impression 3D</a>
        <a href="#" class="link">A propos</a>
        <a href="#" class="link">Contact</a>
        <a href="#" class="link">Connexion</a>
    </nav>
</header>


<main>
  <!-- ¿ inclure $vue? -->

   
</main>



<footer class="fullDisplay">

<nav class="content">
    <a href="index.php">Retour Acceuil</a>
    <a href="#">Mentions légales</p>
    

</nav>

</footer>
<script type="text/javascript" charset="utf-8">
        $(window).load(function() {
        $('.flexslider').flexslider();
        });
    </script>
</html>