<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta description="Busy Designs - LOREM IPSUM">
    
    <script src="js/jquery-3.3.1.min.js" type="text/javascript"></script>
    <script src="js/script.js"></script>

    <!-- SLIDER -->
    <link rel="stylesheet" href="js/slider/flexslider.css" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
    <script src="js/slider/jquery.flexslider.js"></script>
    

    <!-- FIN SLIDER -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,400" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">

    
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/main.css">
   
   

    <title>Busy Designs - Acceuil</title>
</head>

<header class="fullDisplay jsFixed">
    <img src="img/logo.png" class="logo" id="logo" alt="logo">
    <nav class=" noOpacity">   
        <a href="#" class="link fromRight">Réalisations</a>
        <a href="#" class="link">Impression 3D</a>
        <a href="#" class="link">A propos</a>
        <a href="#" class="link">Contact</a>
        <a href="#" class="link">Connexion</a>
    </nav>
</header>


<main>
  <!-- ¿ inclure $vue? -->

    <section class="fullDisplay pitch">
        <div></div>
        <article>
            <h1>Busy Designs</h1>
            <p>Design contemporain, s'adaptant à votre vie.</p>
        </article>
        <div></div>
    </section>
    <section class="fullDisplay">
        <section class="content noOpacity">
            <section class="overView" >
                <article>
                    <span class="fullDisplay"></span>
                    <h2>Réalisations</h2>
                    <div id="slider1" class="flexslider">
                            <ul class="slides">
                                <li>
                                <img src="img/img3.jpg" alt="logo"/>
                                </li>
                                <li>
                                <img src="img/img2.jpg" alt="logo"/>
                                </li>
                                <li>
                                <img src="img/img1.jpg" alt="logo"/>
                                </li>
                            </ul>
                    </div>
                    <span>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores enim maiores, odit eius nesciunt neque consectetur deserunt ipsum optio cumque deleniti atque distinctio porro ut at, obcaecati doloremque. Nobis ipsam inventore magni, accusamus corrupti minus provident ratione ad sapiente iure quo, maxime aliquam, distinctio sed in quos similique deserunt a debitis nostrum culpa at saepe doloribus. Architecto reprehenderit quos dolorum.
                        </p>
                        <ul>
                            <li><p><a href="#">Realisation 1</a></p></li>
                            <li><p><a href="#">Réalisation 2</a></p></li>
                            <li><p><a href="#">Réalisation 3</a></p></li>
                        </ul>
                    </span>

                </article>

                <article>
                    <span></span>
                    <h2>Impressions 3D</h2>
                    <span>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores enim maiores, odit eius nesciunt neque consectetur deserunt ipsum optio cumque deleniti atque distinctio porro ut at, obcaecati doloremque. Nobis ipsam inventore magni, accusamus corrupti minus provident ratione ad sapiente iure quo, maxime aliquam, distinctio sed in quos similique deserunt a debitis nostrum culpa at saepe doloribus. Architecto reprehenderit quos dolorum.
                        </p>
                    </span>
                    <div id="slider1" class="flexslider">
                                <ul class="slides">
                                    <li>
                                    <img src="img/img1.jpg" alt="logo"/>
                                    </li>
                                    <li>
                                    <img src="img/img2.jpg" alt="logo"/>
                                    </li>
                                    <li>
                                    <img src="img/img3.jpg" alt="logo"/>
                                    </li>
                                </ul>
                    </div>
                </article>

                <article >
                    <span></span>
                    <h2>A Propos</h2>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores enim maiores, odit eius nesciunt neque consectetur deserunt ipsum optio cumque deleniti atque distinctio porro ut at, obcaecati doloremque. Nobis ipsam inventore magni, accusamus corrupti minus provident ratione ad sapiente iure quo, maxime aliquam, distinctio sed in quos similique deserunt a debitis nostrum culpa at saepe doloribus. Architecto reprehenderit quos dolorum.
                    </p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores enim maiores, odit eius nesciunt neque consectetur deserunt ipsum optio cumque deleniti atque distinctio porro ut at, obcaecati doloremque. Nobis ipsam inventore magni, accusamus corrupti minus provident ratione ad sapiente iure quo, maxime aliquam, distinctio sed in quos similique deserunt a debitis nostrum culpa at saepe doloribus. Architecto reprehenderit quos dolorum.
                    </p>
                </article>
            </section>    
        </section>
    </section>    
</main>



<footer class="fullDisplay">

<nav class="content">
    <a href="index.php">Retour Acceuil</a>
    <a href="#">Mentions légales</p>
    

</nav>

</footer>
<script type="text/javascript" charset="utf-8">
        $(window).load(function() {
        $('.flexslider').flexslider();
        });
    </script>
</html>